[package]
name        = "concurrency_threads_and_channels"
version     = "0.1.0"
edition.workspace     = true
rust-version.workspace = true

[[bin]]
name = "threads"
path = "src/bin/threads.rs"

[[bin]]
name = "channels"
path = "src/bin/channels.rs"

[[bin]]
name = "shared_state"
path = "src/bin/shared_state.rs"

[[bin]]
name = "send_sync"
path = "src/bin/send_sync.rs"
