[package]
name        = "collections_and_iterators"
version     = "0.1.0"
edition.workspace     = true
rust-version.workspace = true

[[bin]]
name = "vec_collections"
path = "src/bin/vec_collections.rs"

[[bin]]
name = "hashmap_hashset"
path = "src/bin/hashmap_hashset.rs"

[[bin]]
name = "iterators"
path = "src/bin/iterators.rs"

[[bin]]
name = "custom_iterators"
path = "src/bin/custom_iterators.rs"
